// common constants
const uint chunkSize = 32u;
const uint viewSize = 12u;

const uint axisSize = (chunkSize*viewSize);
const float center = float(viewSize)/2.0*float(chunkSize);
const uint chunkProbes = chunkSize*chunkSize*chunkSize;
const uint viewChunks = viewSize*viewSize*viewSize;

const uint empty = 0xFFFFFFFFu;

const int raySteps = 160;
const float e = 0.01; // max precision of 8 bit float
const float dMin = -sqrt(2.0); // important to allow negative sdf distance data encoding.