// material data

struct material {
    vec4 color;
    float emissive;
    float reflective;
    float opacity;
};

material materials[10] = {
    material(vec4(0.1,0.7,0.1,1.0), 0.0, 1.0, 0.0), // green 1
    material(vec4(0.1,0.8,0.0,1.0), 0.0, 0.0, 0.0), // green 2
    material(vec4(1.0,0.3,0.5,1.0), 0.0, 0.0, 0.0), // and so on
    material(vec4(1.0,0.5,0.1,1.0), 0.0, 0.0, 0.0),
    material(vec4(0.6,0.3,0.0,1.0), 0.0, 0.0, 0.0),
    material(vec4(0.5,0.5,0.5,1.0), 0.0, 0.0, 0.0),
    material(vec4(0.5,0.5,0.1,1.0), 0.0, 0.0, 0.0),
    material(vec4(1.0,0.0,0.0,1.0), 5.0, 1.0, 0.0),
    material(vec4(1.0), 0.0, 10.0, 0.0),
    material(vec4(0.4,0.6,1.0,1.0), 0.0, 1.0, 0.0)
};