// includes setters and getters for geometry
// p is global position vec3, lp is local position v3(0:x) blocks in view
// use local pos for all sampling to keep camera centered within chunks

// not to be used for indexing, just clamps position physically to chunk border
vec3 getChunkPos(vec3 p) {
    return floor(p / chunkSize) * chunkSize;
}

// takes chunk position and spits out index in prefix array

// will handle chunk shuffling, ie getting chunk pos, and matching to actual position, before updating, as well as matching to chunk position
// also need to handle global position offset, ie: chunks player has travelled in each direction.
uvec3 getLocalPos(vec3 p, vec3 worldPos) {
    uvec3 lp = (uvec3(mod(floor(p)+worldPos, axisSize)));
    return lp;
}

// gets index in chunk prefix array from position
uint posToChunkIndex(uvec3 lp) {
    uvec3 cp = lp/chunkSize;
    return cp.x+viewSize*(cp.y+viewSize*cp.z);
}

// takes position in chunk, and uses chunk data previously set to get index.
uint posToIndex(uvec3 lp) {
    uint slot = chunkData[posToChunkIndex(lp)];
    if (slot == unloaded) return unloaded; // early out for unloaded indexes

    // local positioning
    uvec3 pp = lp % chunkSize;
    uint i = pp.x+chunkSize*(pp.y+chunkSize*pp.z);

    // combine
    return slot*chunkProbes+i;
    //return lp.x+axisSize*(lp.y+axisSize*lp.z);
}

// sets probe with 8 bit packing
void setProbe(uint index, float d) {
    uint uintIndex = index >> 2u; // divide by 4 (shift/half twice)
    uint subIndex = index & 3u;
    uint bitShift = subIndex * 8u; // bit shift

    vec4 probes = vec4(0.0);

    probes[subIndex] = (d-dMin) / float(chunkSize); // set distance, normalized to 0-1

    uint packedProbe = packUnorm4x8(probes);
    uint clearMask = ~(0xFFu << bitShift); // clear bit

    atomicAnd(probeData[uintIndex], clearMask);
    atomicOr(probeData[uintIndex], packedProbe); // set value. need clear mask if overwriting
}

// sets material with 4 bit packing
void setMaterial(uint index, uint m) {
    uint uintIndex = index >> 3u; // divide by 8
    uint bitShift = (index & 7u) * 4u; // bit shift

    uint insert = (m & 0xFu) << bitShift;
    uint clearMask = ~(0xFu << bitShift); // clear bit

    atomicAnd(materialData[uintIndex], clearMask);
    atomicOr(materialData[uintIndex], insert); // set value. need clear mask if overwriting
}

// gets probe with 8 bit packing
float getProbe(uint index) {
    //uint index = posToIndex(lp);
    if (index == unloaded) return 1.0; // safety for empties, 1.0 seems to work, likely because chunk clamping off by around this

    uint uintIndex = index >> 2u;
    uint subIndex = index & 3u;

    vec4 values = unpackUnorm4x8(probeData[uintIndex]);

    return ((values[subIndex]*float(chunkSize))+dMin);
}

// gets material with 4 bit packing
uint getMaterial(uint index) {
    //uint index = posToIndex(lp);
    uint uintIndex = index >> 3u;
    uint bitShift = (index & 7u) * 4u; // shift amount

    return (materialData[uintIndex] >> bitShift) & 0xFu;
}

// sets chunk flag, uses last index of chunkData to store.
void updateStoreFlag(float d, uint slot) {
    if (d>dMin && d<e) chunkData[viewChunks+slot] = stored;
}

uint getStoreFlag(uint slot) {
    return chunkData[viewChunks+slot];
}

void setStoreFlag(uint slot, uint flag) {
    chunkData[viewChunks+slot] = flag;
}