// applies affects to probes, as well as make sampling come from position
float getProbeWarped(vec3 p) {
    uvec3 lp = getLocalPos(p, worldPos);
    uint index = posToIndex(lp);
    //float warp = (sin(p.y/5.0)-1.0)/2.0;
    return getProbe(index);//+warp;
}

float getColliderDist(vec3 p) {
    uvec3 lp = getLocalPos(p,worldPos);
    if (posToIndex(lp)==unloaded) return 1.0; // safety

    uint index = posToCollisionIndex(lp);
    
    // just getProbe code
    uint uintIndex = index >> 2u;
    uint subIndex = index & 3u;

    vec4 values = unpackUnorm4x8(colliderData[uintIndex]);

    return ((values[subIndex]*float(chunkSize))+dMin);
}

// interpolates between surrounding precomputed collider probe distances.
float smoothColliderDist(vec3 p) {
    float s = float(simFidelity);
    vec3 f = mod(p,s)/s;

    // get all probes
    float d000 = getColliderDist(p + vec3(0,0,0)*simFidelity);
    float d100 = getColliderDist(p + vec3(1,0,0)*simFidelity);
    float d010 = getColliderDist(p + vec3(0,1,0)*simFidelity);
    float d110 = getColliderDist(p + vec3(1,1,0)*simFidelity);
    float d001 = getColliderDist(p + vec3(0,0,1)*simFidelity);
    float d101 = getColliderDist(p + vec3(1,0,1)*simFidelity);
    float d011 = getColliderDist(p + vec3(0,1,1)*simFidelity);
    float d111 = getColliderDist(p + vec3(1,1,1)*simFidelity);

    // x interpolation
    float x00 = mix(d000, d100, f.x);
    float x10 = mix(d010, d110, f.x);
    float x01 = mix(d001, d101, f.x);
    float x11 = mix(d011, d111, f.x);

    // y interpolation
    float y0 = mix(x00, x10, f.y);
    float y1 = mix(x01, x11, f.y);

    // z interpolation
    float d = mix(y0, y1, f.z);

    return d; // adjust for negative distances
}

// interpolates between surrounding precomputed probe distances.
float smoothDist(vec3 p) {
    vec3 f = fract(p);

    // get all probes
    float d000 = getProbeWarped(p + vec3(0,0,0));
    float d100 = getProbeWarped(p + vec3(1,0,0));
    float d010 = getProbeWarped(p + vec3(0,1,0));
    float d110 = getProbeWarped(p + vec3(1,1,0));
    float d001 = getProbeWarped(p + vec3(0,0,1));
    float d101 = getProbeWarped(p + vec3(1,0,1));
    float d011 = getProbeWarped(p + vec3(0,1,1));
    float d111 = getProbeWarped(p + vec3(1,1,1));

    // x interpolation
    float x00 = mix(d000, d100, f.x);
    float x10 = mix(d010, d110, f.x);
    float x01 = mix(d001, d101, f.x);
    float x11 = mix(d011, d111, f.x);

    // y interpolation
    float y0 = mix(x00, x10, f.y);
    float y1 = mix(x01, x11, f.y);

    // z interpolation
    float d = mix(y0, y1, f.z);

    return d; // adjust for negative distances
}

vec4 smoothColor(vec3 p) {
    vec3 f = sqrt(fract(p));
    
    // need empty borders check so things close to edge don't sample green.
    vec4 c000 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,0,0),worldPos)))].color;
    vec4 c100 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,0,0),worldPos)))].color;
    vec4 c010 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,1,0),worldPos)))].color;
    vec4 c110 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,1,0),worldPos)))].color;
    vec4 c001 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,0,1),worldPos)))].color;
    vec4 c101 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,0,1),worldPos)))].color;
    vec4 c011 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,1,1),worldPos)))].color;
    vec4 c111 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,1,1),worldPos)))].color;

    // x interpolation
    vec4 x00 = mix(c000, c100, f.x);
    vec4 x10 = mix(c010, c110, f.x);
    vec4 x01 = mix(c001, c101, f.x);
    vec4 x11 = mix(c011, c111, f.x);

    // y interpolation
    vec4 y0 = mix(x00, x10, f.y);
    vec4 y1 = mix(x01, x11, f.y);

    // z interpolation
    vec4 c = mix(y0, y1, f.z);

    return c; // adjust for negative distances
}

float smoothEmissive(vec3 p) {
    vec3 f = fract(p);
    
    // need empty borders check so things close to edge don't sample green.
    float c000 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,0,0),worldPos)))].emissive;
    float c100 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,0,0),worldPos)))].emissive;
    float c010 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,1,0),worldPos)))].emissive;
    float c110 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,1,0),worldPos)))].emissive;
    float c001 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,0,1),worldPos)))].emissive;
    float c101 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,0,1),worldPos)))].emissive;
    float c011 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(0,1,1),worldPos)))].emissive;
    float c111 = materials[getMaterial(posToIndex(getLocalPos(p + vec3(1,1,1),worldPos)))].emissive;

    // x interpolation
    float x00 = mix(c000, c100, f.x);
    float x10 = mix(c010, c110, f.x);
    float x01 = mix(c001, c101, f.x);
    float x11 = mix(c011, c111, f.x);

    // y interpolation
    float y0 = mix(x00, x10, f.y);
    float y1 = mix(x01, x11, f.y);

    // z interpolation
    float c = mix(y0, y1, f.z);

    return c; // adjust for negative distances
}

// Paulo Falcao technique
vec3 getNormal(vec3 p) {
    const float h = e*20.0; // higher coefficient makes things look smoother
    const vec2 k = vec2(1.0,-1.0);
    
    return normalize(k.xyy*smoothDist(p+k.xyy*h) + 
                     k.yyx*smoothDist(p+k.yyx*h) + 
                     k.yxy*smoothDist(p+k.yxy*h) + 
                     k.xxx*smoothDist(p+k.xxx*h));
}

// camera shizzle
vec3 getRayDir(vec2 fragCoord, vec2 res, vec3 lookAt, float zoom) {
    vec2 uv = (fragCoord - 0.5 * res) / res.y;
    vec3 f = normalize(lookAt);
    vec3 r = normalize(cross(vec3(0.0,1.0,0.0), f));
    vec3 u = cross(f,r);
    return normalize(f + zoom * (uv.x*r + uv.y*u));
}

// returns distance to chunk edge
float distToBorder(vec3 pp, vec3 rd, vec3 l) {
    vec3 border = mix(vec3(0.0), l, step(0.0, rd));
    vec3 t = (border - pp) / rd;
    return min(min(t.x, t.y), t.z);
}