// sphere sdf
float sphere(vec3 p, float r) {
    return length(p)-r;
}

// cube sdf
float box(vec3 p, vec3 b) {
    vec3 d = abs(p) - b;
    return min(max(d.x,max(d.y,d.z)),0.0) + length(max(d,0.0));
}

float cylinder(vec3 p, float r, float h) {
  vec2 d = abs(vec2(length(p.xz),p.y)) - vec2(r,h);
  return min(max(d.x,d.y),0.0) + length(max(d,0.0));
}

// basic hash function
float hash(vec3 p3) {
    p3 = fract(p3 * 0.1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

// basic 3d hash function
vec3 hash3(vec3 p) {
    p = fract(p * vec3(443.897, 441.423, 437.195));
    p += dot(p, p.yxz + 19.19);
    return fract(vec3((p.x + p.y) * p.z, (p.x + p.z) * p.y, (p.y + p.z) * p.x)) * 2.0 - 1.0;
}

// fast random unit vector approximation
vec3 randomUnitVector(vec3 p) {
    vec3 r = hash3(p);
    return normalize(tan(hash3(r)));
}
