// world settings
const uint chunkSize = 32u;
const uint viewSize = 32u;

// world data
const uint axisSize = (chunkSize*viewSize);
const float center = float(viewSize)/2.0*float(chunkSize);
const uint chunkProbes = chunkSize*chunkSize*chunkSize;
const uint viewChunks = viewSize*viewSize*viewSize;

// flag for if chunk isn't loaded
const uint unloaded = 0xFFFFFFFFu;

// enum flags for chunk state
const uint unstored = 2u; // unloaded
const uint stored = 1u; // loaded
const uint generating = 0u; // currently generating

// collider building
const uint simSize = 16*32; // amount of chunks in simulation distance
const uint simProbes = simSize*simSize*simSize;
const uint simFidelity = 8; // amount to cut collision buffer detail by in each axis

// rendering constants
const int raySteps = 160;
const float e = 0.01; // max precision of 8 bit float
const float renderDist = float(viewSize*chunkSize)/2.1; // max ray distance
const float dMin = -sqrt(2.0); // important to allow negative sdf distance data encoding.