// includes setters and getters for geometry
// p is global position vec3, lp is local uvec3 in chunk, cp is chunk uvec3


uvec3 getLocalPos(vec3 p) {
    return uvec3(floor(p))%chunkSize;
}

// takes position in chunk, and chunk size, and spits out positional index in chunkSize^3 array.
uint posToIndex(uvec3 lp) {
    return lp.x+chunkSize*(lp.y+chunkSize*lp.z);
}

// takes position and spits out the index of chunk it is in
uint getChunkIndex(vec3 p) {
    uvec3 cp = uvec3(floor(p/float(chunkSize))); // gets chunk position
    uint i = cp.x+viewSize*(cp.y+viewSize*cp.z); // index of chunk
    return chunkIndexes[i];
    //return 0;
}

// sets probe with 8 bit packing
void setProbe(uvec3 lp, uint cIndex, float d) {
    uint index = posToIndex(lp)+cIndex;
    uint uintIndex = index >> 2u;
    uint subIndex = index & 3u;
    uint bitShift = subIndex * 8u; // bit shift

    vec4 probes = vec4(0.0);

    probes[subIndex] = (d-dMin) / float(chunkSize); // set distance, normalized to 0-1

    uint packedProbe = packUnorm4x8(probes);
    uint clearMask = ~(0xFFu << bitShift); // clear bit

    atomicAnd(probeData[uintIndex], clearMask);
    atomicOr(probeData[uintIndex], packedProbe); // set value. need clear mask if overwriting
}

// sets material with 4 bit packing
void setMaterial(uvec3 lp, uint cIndex, uint m) {
    uint index = posToIndex(lp)+cIndex;
    uint uintIndex = index >> 3u;
    uint bitShift = (index & 7u) * 4u; // bit shift

    uint insert = (m & 0xFu) << bitShift;
    uint clearMask = ~(0xFu << bitShift); // clear bit

    atomicAnd(materialData[uintIndex], clearMask);
    atomicOr(materialData[uintIndex], insert); // set value. need clear mask if overwriting
}

// gets probe with 8 bit packing
float getProbe(uvec3 p, uint cIndex) {
    uint index = posToIndex(p)+cIndex;
    uint uintIndex = index >> 2u;
    uint subIndex = index & 3u;

    vec4 values = unpackUnorm4x8(probeData[uintIndex]);

    return ((values[subIndex]*float(chunkSize))+dMin);
}

// gets material with 4 bit packing
uint getMaterial(uvec3 p, uint cIndex) {
    uint index = posToIndex(p)+cIndex;
    uint uintIndex = index >> 3u;
    uint bitShift = (index & 7u) * 4u; // shift amount

    return (materialData[uintIndex] >> bitShift) & 0xFu;
}