#version 430 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

uniform vec3 uPos = vec3(32,32,32); // position of edit
uniform float uSize = 6.0; // size of edit 
uniform uint uType = 0; // type of edit
uniform uint uMaterial = 7;
uniform int uPlace = 0; // -1:place or 1:break

//include shaders/4.3.constantsH.comp
//include shaders/4.3.functionsH.comp

// sets probe with 8 bit packing
void setProbe(uvec3 p, float d) {
    uint index = posToIndex(p);
    uint uintIndex = index >> 2u;
    uint subIndex = index & 3u;
    uint bitShift = subIndex * 8u; // bit shift

    vec4 probes = vec4(0.0);

    probes[subIndex] = (d-dMin) / float(chunkSize); // set distance, normalized to 0-1

    uint packedProbe = packUnorm4x8(probes);
    uint clearMask = ~(0xFFu << bitShift); // clear bit

    atomicAnd(probeData[uintIndex], clearMask);
    atomicOr(probeData[uintIndex], packedProbe); // set value. need clear mask if overwriting
}

// sets material with 4 bit packing
void setMaterial(uvec3 p, uint m) {
    uint index = posToIndex(p);
    uint uintIndex = index >> 3u;
    uint bitShift = (index & 7u) * 4u; // bit shift

    uint insert = (m & 0xFu) << bitShift;
    uint clearMask = ~(0xFu << bitShift); // clear bit

    atomicAnd(materialData[uintIndex], clearMask);
    atomicOr(materialData[uintIndex], insert); // set value. need clear mask if overwriting
}

float getProbe(uvec3 p) {
    uint index = posToIndex(p);
    uint uintIndex = index >> 2u;
    uint subIndex = index & 3u;

    vec4 values = unpackUnorm4x8(probeData[uintIndex]);

    return ((values[subIndex]*float(chunkSize))+dMin);
}

// gets edit function at position and size
float getEdit(vec3 p, uint i, float s) {
    switch (i) {
        case 0:
            return sphere(p, s);
        case 1:
            return box(p, vec3(s));
        default:
            return sphere(p, s);
    }
}

void main() {
    uvec3 p = gl_GlobalInvocationID; // probe position

    float nd = getEdit(p-uPos, uType, uSize); // gets new distance
    float od = getProbe(p); // gets current distance
    if (uPlace == -1) {
        if (nd<od) { // placing
            //setMaterial(p,uMaterial);
            setProbe(p,nd);
        }
    } else {
        if (-nd>od) { // breaking
            //setMaterial(p,uMaterial);
            setProbe(p,-nd);
        }
    }

    // maybe implement neighbor check for unreset probes
}