#version 440 core

layout(local_size_x = 8, local_size_y = 8) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

layout(std430, binding = 2) buffer ChunkData {
    uint chunkData[];
};

layout(std430, binding = 3) buffer ColliderData { // temp for collider view
    uint colliderData[];
};


// player data
uniform vec3 pPos = vec3(0.0,0.0,-1.0);
uniform vec3 worldPos;
uniform vec3 pDir = vec3(0.0,0.0,1.0);

// screen data
layout(rgba32f, binding=0) uniform writeonly image2D screen;
uniform int screenWidth = 1;
uniform int screenHeight = 1;
uniform float iTime;

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.materialsH.comp
//include shaderheaders/4.3.setgetH.comp

// applies affects to probes, as well as make sampling come from position
float getProbeWarped(vec3 p) {
    uvec3 lp = getLocalPos(p, worldPos);
    uint index = posToIndex(lp);
    //float warp = (sin(p.y/5.0)-1.0)/2.0;
    return getProbe(index);//+warp;
}

float getColliderDist(vec3 p) {
    uvec3 lp = getLocalPos(p,worldPos);
    if (posToIndex(lp)==unloaded) return 1.0; // safety

    uint index = posToCollisionIndex(lp);
    
    // just getProbe code
    uint uintIndex = index >> 2u;
    uint subIndex = index & 3u;

    vec4 values = unpackUnorm4x8(colliderData[uintIndex]);

    return ((values[subIndex]*float(chunkSize))+dMin);
}

// interpolates between surrounding precomputed collider probe distances.
float smoothColliderDist(vec3 p) {
    float s = float(simFidelity);
    vec3 f = mod(p,s)/s;

    // get all probes
    float d000 = getColliderDist(p + vec3(0,0,0)*simFidelity);
    float d100 = getColliderDist(p + vec3(1,0,0)*simFidelity);
    float d010 = getColliderDist(p + vec3(0,1,0)*simFidelity);
    float d110 = getColliderDist(p + vec3(1,1,0)*simFidelity);
    float d001 = getColliderDist(p + vec3(0,0,1)*simFidelity);
    float d101 = getColliderDist(p + vec3(1,0,1)*simFidelity);
    float d011 = getColliderDist(p + vec3(0,1,1)*simFidelity);
    float d111 = getColliderDist(p + vec3(1,1,1)*simFidelity);

    // x interpolation
    float x00 = mix(d000, d100, f.x);
    float x10 = mix(d010, d110, f.x);
    float x01 = mix(d001, d101, f.x);
    float x11 = mix(d011, d111, f.x);

    // y interpolation
    float y0 = mix(x00, x10, f.y);
    float y1 = mix(x01, x11, f.y);

    // z interpolation
    float d = mix(y0, y1, f.z);

    return d; // adjust for negative distances
}

// interpolates between surrounding precomputed probe distances.
float smoothDist(vec3 p) {
    vec3 f = fract(p);

    // get all probes
    float d000 = getProbeWarped(p + vec3(0,0,0));
    float d100 = getProbeWarped(p + vec3(1,0,0));
    float d010 = getProbeWarped(p + vec3(0,1,0));
    float d110 = getProbeWarped(p + vec3(1,1,0));
    float d001 = getProbeWarped(p + vec3(0,0,1));
    float d101 = getProbeWarped(p + vec3(1,0,1));
    float d011 = getProbeWarped(p + vec3(0,1,1));
    float d111 = getProbeWarped(p + vec3(1,1,1));

    // x interpolation
    float x00 = mix(d000, d100, f.x);
    float x10 = mix(d010, d110, f.x);
    float x01 = mix(d001, d101, f.x);
    float x11 = mix(d011, d111, f.x);

    // y interpolation
    float y0 = mix(x00, x10, f.y);
    float y1 = mix(x01, x11, f.y);

    // z interpolation
    float d = mix(y0, y1, f.z);

    return d; // adjust for negative distances
}

vec4 smoothColor(vec3 p) {
    vec3 f = fract(p);
    
    // need empty borders check so things close to edge don't sample green.
    vec4 c000 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(0,0,0),worldPos)))];
    vec4 c100 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(1,0,0),worldPos)))];
    vec4 c010 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(0,1,0),worldPos)))];
    vec4 c110 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(1,1,0),worldPos)))];
    vec4 c001 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(0,0,1),worldPos)))];
    vec4 c101 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(1,0,1),worldPos)))];
    vec4 c011 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(0,1,1),worldPos)))];
    vec4 c111 = colors[getMaterial(posToIndex(getLocalPos(p + vec3(1,1,1),worldPos)))];

    // x interpolation
    vec4 x00 = mix(c000, c100, f.x);
    vec4 x10 = mix(c010, c110, f.x);
    vec4 x01 = mix(c001, c101, f.x);
    vec4 x11 = mix(c011, c111, f.x);

    // y interpolation
    vec4 y0 = mix(x00, x10, f.y);
    vec4 y1 = mix(x01, x11, f.y);

    // z interpolation
    vec4 c = mix(y0, y1, f.z);

    return c; // adjust for negative distances
}

// Paulo Falcao technique
vec3 getNormal(vec3 p) {
    const float h = e*20.0; // higher coefficient makes things look smoother
    const vec2 k = vec2(1.0,-1.0);
    
    return normalize(k.xyy*smoothDist(p+k.xyy*h) + 
                     k.yyx*smoothDist(p+k.yyx*h) + 
                     k.yxy*smoothDist(p+k.yxy*h) + 
                     k.xxx*smoothDist(p+k.xxx*h));
}

// camera shizzle
vec3 getRayDir(vec2 fragCoord, vec2 res, vec3 lookAt, float zoom) {
    vec2 uv = (fragCoord - 0.5 * res) / res.y;
    vec3 f = normalize(lookAt);
    vec3 r = normalize(cross(vec3(0.0,1.0,0.0), f));
    vec3 u = cross(f,r);
    return normalize(f + zoom * (uv.x*r + uv.y*u));
}

// returns distance to chunk edge
float distToBorder(vec3 pp, vec3 rd, vec3 l) {
    vec3 border = mix(vec3(0.0), l, step(0.0, rd));
    vec3 t = (border - pp) / rd;
    return min(min(t.x, t.y), t.z);
}

void main() {
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);

    // crosshair
    vec2 crossHair = fragCoord-vec2(screenWidth,screenHeight)/2.0;
    if (dot(crossHair,crossHair) < 64.0) return;

    // marching
    float t = 0.0;
    vec3 ro = pPos-worldPos+center; // ray pos local to view
    vec3 rd = getRayDir(fragCoord, vec2(screenWidth,screenHeight),pDir,1.0);
    float collect = 0.0;
    for (int i = 0; i < raySteps; i++) {
        if (t>renderDist) break; // early out

        vec3 p = ro+rd*t; // calculate ray position
        if (clamp(p, vec3(0.0), vec3(chunkSize*viewSize)) != p) break; // borders (temp)

        // distance to chunk border
        //collect += float(chunkData[posToChunkIndex(getLocalPos(p, worldPos))]/chunkProbes)/float(viewChunks*100);
        float cd = distToBorder(mod(p,float(chunkSize)), rd, vec3(chunkSize))+e;
        uint slot = chunkData[posToChunkIndex(getLocalPos(p, worldPos))];
        if (slot == unloaded || getStoreFlag(slot) == generating) { // if in unloaded, skip
            t+=cd+e;
            continue;
        }

        // distance to surface
        float d = smoothDist(p);
        if (cd<d) {
            //collect += 0.1;
            collect = min(collect, 0.5);
        }

        // hit
        if (d < e) { 
            // coloring and stuff
            //t/float(full)*2.1
            float falloff = min(
                            max(t/renderDist,
                                float(i)/float(raySteps))
                            ,1.0);
            float shadow = max(dot(getNormal(p),vec3(1.0)),0.3); // basic shading
            vec4 color = smoothColor(p);
            //if (getColliderDist(p) < e) color = vec4(1.0);

            imageStore(screen, fragCoord, mix(color*shadow,vec4(0.0,0.4,1.0,1.0),pow(falloff, 18.0))+collect);
            return;
        }

        t+=min(max(d,e),cd); // step ray
    }
    imageStore(screen, fragCoord, vec4(0.0,0.4,1.0,1.0)+collect);
}
