#version 440 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

layout(std430, binding = 2) buffer ChunkData {
    uint chunkData[];
};

layout(std430, binding = 3) buffer ColliderData { // temp for collider view
    uint colliderData[];
};

layout(binding = 1) uniform sampler2D depthMap; // depth and normal map
layout(rgba32f, binding=2) uniform writeonly image3D lightMap; // lighting map

uniform int screenWidth = 1;
uniform int screenHeight = 1;
uniform int lightSamples = 1;
uniform int lightFidelity = 1;
uniform int lightFrame = 1;
uniform vec3 worldPos;
uniform vec3 pPos;
uniform vec3 pDir;
uniform float iTime;

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.materialsH.comp
//include shaderheaders/4.3.setgetH.comp
//include shaderheaders/4.3.raysH.comp

vec4 lightRay(vec3 ro, vec3 rd, vec3 sun) {

    // marching
    float t = 0.1;
    vec3 surfaceNormal = rd;
    
    vec4 color = smoothColor(ro)*smoothEmissive(ro);
    float remain = 1.0; // remaining energy after bounces
    for (int i = 0; i < lightSteps; i++) {

        vec3 p = ro+rd*t; // calculate ray position

        // distance to chunk border
        float cd = distToBorder(mod(p,float(chunkSize)), rd, vec3(chunkSize))+e;
        uint slot = chunkData[posToChunkIndex(getLocalPos(p, worldPos))];
        if (slot == unloaded || getStoreFlag(slot) == generating) { // if in unloaded, skip
            t+=cd+e;
            continue;
        }

        // distance to surface
        float d = smoothDist(p);
        t+=min(max(d,1.0),cd); // step ray

        // hit
        if (d < 0.1) {
            uint m = getMaterial(posToIndex(getLocalPos(p,worldPos)));
            color += 3*materials[m].color*(materials[m].emissive+materials[m].reflective);
            remain *= 0.8; // lose energy
            if (remain <0.6) break; // too much energy loss

            // reflecting handling
            vec3 normal = getNormal(p);
            rd=reflect(rd,normal);
            t=0.1; // reset t
        }
    }
    // if rays travel far enough on last bounce, get sun, otherwise make them dark
    float sunLight = max(dot(surfaceNormal, sun),0.3);
    return (color+1)*remain;
}

void main() {
    ivec3 fragCoord = ivec3(gl_GlobalInvocationID.xyz); // light screen coordinates
    vec2 uv = vec2(gl_GlobalInvocationID.xy) / vec2(screenWidth, screenHeight); // sample from normal screen coords
    int seed = fragCoord.z+lightFrame*lightSamples;
    vec4 depth = texture(depthMap, uv);
    vec3 normal = depth.xyz;

    // reconstruct position on surface of ray
    vec3 rd = getRayDir(fragCoord.xy, vec2(screenWidth,screenHeight),pDir,1.0);
    vec3 ro = pPos-worldPos+center+rd*depth.w+normal;

    // create random vector within normal hemisphere
    float it = sin(iTime); 
    vec3 nrd = randomUnitVector(fragCoord*float(seed)*it);
    if (dot(nrd,normal)<0) nrd = -nrd; // flip if outside of hemisphere

    // cast ray from surface
    vec3 sun = normalize(vec3(sin(iTime/10.0), 1.0, cos(iTime/20.0)));
    vec4 color = lightRay(ro, nrd, sun);

    // store light value
    imageStore(lightMap, ivec3(fragCoord.xy,seed), color);
}