#version 440 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

layout(std430, binding = 2) buffer ChunkData {
    uint chunkData[];
};

layout(std430, binding = 3) buffer ColliderData { // temp for collider view
    uint colliderData[];
};

layout(binding = 1) uniform sampler2D depthMap; // depth and normal map
layout(rgba32f, binding=2) uniform writeonly image3D lightMap; // lighting map

uniform int screenWidth = 1;
uniform int screenHeight = 1;
uniform int lightSamples = 1;
uniform int lightFidelity = 1;
uniform int lightFrame = 1;
uniform vec3 worldPos;
uniform vec3 pPos;
uniform vec3 pDir;
uniform float iTime;

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.materialsH.comp
//include shaderheaders/4.3.setgetH.comp
//include shaderheaders/4.3.samplingH.comp

vec4 lightRay(vec3 ro, vec3 rd) {
    // marching
    vec4 color = smoothColor(ro)*smoothEmissive(ro);
    uint hitM = getMaterial(posToIndex(getLocalPos(ro,worldPos)));
    float reflectiveness = materials[hitM].reflective;
    float remain = 1.0; // remaining energy after bounces
    float t = 0.1;

    for (int i = 0; i < lightSteps; i++) {

        vec3 p = ro+rd*t; // calculate ray position

        // distance to chunk border
        float cd = distToBorder(mod(p,float(chunkSize)), rd, vec3(chunkSize))+e;
        uint slot = chunkData[posToChunkIndex(getLocalPos(p, worldPos))];
        if (slot == unloaded || getStoreFlag(slot) == generating) { // if in unloaded, skip
            t+=cd+e;
            continue;
        }

        // distance to surface
        float d = getProbeWarped(p);
        if (d<5.0) d = smoothDist(p);
        t+=max(min(d,cd),1.0); // step ray

        // hit
        if (d < 0.1) {
            uint m = getMaterial(posToIndex(getLocalPos(p,worldPos)));
            color += materials[m].color*(materials[m].emissive);
            remain *= 0.3+materials[m].emissive; // lose energy
            if (remain <0.05) break; // too much energy loss
            if (remain >1.0) break; // too much energy gain

            // reflecting handling
            rd=reflect(rd,getNormal(p));
            t=0.1; // reset t
        }
    }
    
    return (1+color)*remain;
}

void main() {
    ivec3 fragCoord = ivec3(gl_GlobalInvocationID.xyz); // light screen coordinates
    if (fragCoord.z>lightSamples) return; // early out for safety

    // sample from normal screen coords
    vec2 uv = vec2(gl_GlobalInvocationID.xy) / vec2(screenWidth, screenHeight);
    int seed = fragCoord.z+lightFrame*lightSamples;
    vec4 depth = texture(depthMap, uv);
    vec3 normal = depth.xyz;

    // reconstruct position on surface of ray
    vec3 rd = getRayDir(fragCoord.xy, vec2(screenWidth,screenHeight),pDir,1.0);
    vec3 ro = pPos-worldPos+center+rd*depth.w+normal;

    // create random vector within normal hemisphere
    vec3 nrd = randomUnitVector(normalize(fragCoord+lightFrame+iTime));
    if (dot(nrd,normal)<0.0) nrd = -nrd; // flip if outside of hemisphere

    // cast ray from surface
    vec4 color = lightRay(ro, nrd);

    // store light value
    imageStore(lightMap, ivec3(fragCoord.xy,seed), color);
}