#version 430 core

layout(local_size_x = 8, local_size_y = 8) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

// player data
uniform vec3 pPos = vec3(0.0,0.0,-1.0);
uniform vec3 pDir = vec3(0.0,0.0,1.0);

// screen data
layout(rgba32f, binding=0) uniform writeonly image2D screen;
uniform int screenWidth = 1;
uniform int screenHeight = 1;
uniform float iTime;

//include shaders/4.3.constantsH.comp
//include shaders/4.3.functionsH.comp
//include shaders/4.3.materialsH.comp

float getProbe(uvec3 p) {
    uint m = posToIndex(p);
    uint uintIndex = m >> 2u;
    uint subIndex = m & 3u;

    vec4 values = unpackSnorm4x8(probeData[uintIndex]);

    return (values[subIndex]*float(chunkSize))+dMin; // can add distance values based on materials
}

vec4 getColor(vec3 p) {
    uvec3 up = uvec3(p);
    float count = 1.0;
    vec4 color = vec4(1.0);
    for (int x = -3; x < 2; x++)
    for (int y = -3; y < 2; y++)
    for (int z = -3; z < 2; z++) {
        float fmaterial = getProbe(up+ivec3(x,y,z))*128.0;
        if (fmaterial > 0.0) break;
        uint umaterial = uint(abs(fmaterial));
        color += colors[umaterial%6u];
        count += 1.0;
    }
    return color/count;

}

// interpolates between surrounding precomputed probe distances.
float smoothDist(vec3 p) {
    uvec3 up = uvec3(floor(p));
    vec3 f = fract(p);
    float d000 = getProbe(up + uvec3(0,0,0));
    float d100 = getProbe(up + uvec3(1,0,0));
    float d010 = getProbe(up + uvec3(0,1,0));
    float d110 = getProbe(up + uvec3(1,1,0));
    float d001 = getProbe(up + uvec3(0,0,1));
    float d101 = getProbe(up + uvec3(1,0,1));
    float d011 = getProbe(up + uvec3(0,1,1));
    float d111 = getProbe(up + uvec3(1,1,1));

    // x interpolation
    float x00 = mix(d000, d100, f.x);
    float x10 = mix(d010, d110, f.x);
    float x01 = mix(d001, d101, f.x);
    float x11 = mix(d011, d111, f.x);

    // y interpolation
    float y0 = mix(x00, x10, f.y);
    float y1 = mix(x01, x11, f.y);

    // z interpolation
    float d = mix(y0, y1, f.z);

    return d; // adjust for negative distances
}

// Paulo Falcao technique
vec3 getNormal(vec3 p) {
    const float h = e*10.0; // replace by an appropriate value
    const vec2 k = vec2(1,-1);
    return normalize(k.xyy*smoothDist(p + k.xyy*h) + 
                     k.yyx*smoothDist(p + k.yyx*h) + 
                     k.yxy*smoothDist(p + k.yxy*h) + 
                     k.xxx*smoothDist(p + k.xxx*h));
}

// camera shizzle
vec3 getRayDir(vec2 fragCoord, vec2 res, vec3 lookAt, float zoom) {
    vec2 uv = (fragCoord - 0.5 * res) / res.y;
    vec3 f = normalize(lookAt);
    vec3 r = normalize(cross(vec3(0.0,1.0,0.0), f));
    vec3 u = cross(f,r);
    return normalize(f + zoom * (uv.x*r + uv.y*u));
}

void main() {
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy);

    // crosshair
    vec2 crossHair = fragCoord-vec2(screenWidth,screenHeight)/2.0;
    if (dot(crossHair,crossHair) < 128.0) return;

    // marching
    float t = 0.0;
    vec3 ro = pPos;
    vec3 rd = getRayDir(fragCoord, vec2(screenWidth,screenHeight),pDir,1.0);
    for (int i = 0; i < raySteps; i++) {
        vec3 p = ro+rd*t;
        //float d = sdBox(p, vec3(4.0));
        float d = smoothDist(p);
        if (d < e) {
            float falloff = t/renderDist;
            float shadow = 1.1-dot(vec3(1.0),getNormal(p)); // basic phong lighting
            vec4 color = getColor(p);
            imageStore(screen, fragCoord, mix(color*shadow,vec4(0.0,0.4,1.0,1.0),falloff));
            return;
        }
        if (clamp(p, vec3(0.0), vec3(chunkSize)) != p) break;
        t+=max(d,e*10.0);
        if (t>renderDist) break;
    }
    imageStore(screen, fragCoord, vec4(0.0,0.4,1.0,1.0));
}
