#version 440 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

layout(std430, binding = 2) buffer ChunkIndexes {
    int chunkIndexes[];
};

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.setgetH.comp

// parameters
uniform vec3 cPos = vec3(0); // position to check chunk at

// Checker can only set to full
// always set the chunk to empty when generating or updating, and have the checker verify that.
void main() {
    uvec3 pp = gl_GlobalInvocationID; // local chunk position
    vec3 p = vec3(pp+cPos); // global position
    uvec3 lp = getLocalPos(p);

    float d = getProbe(lp); // gets distance of probe
    if (d<=0.0) {
        chunkIndexes[posToChunkIndex(p)] = 1;
    }
}