#version 440 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

layout(std430, binding = 2) buffer IndexData {
    uint indexData[];
};

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.setgetH.comp

// parameters
uniform uint slot; // slot in buffers to generate at
uniform uint cIndex; // chunk index that stores slot
uniform vec3 cPos; // global position for generation

float smin(float a, float b, float k) {
    float h = max(k-abs(a-b),0.0);
    return min(a, b) - h*h*0.25/k;
}

float smax(float a, float b, float k) {
    float h = max(k-abs(a-b),0.0);
    return max(a, b) + h*h*0.25/k;
}

float trees(vec3 p3, float s, float l) {
    vec2 p = p3.xz;
    vec2 id = round(p/s);
    vec2  o = sign(p-s*id); // neighbor offset direction
    
    float d = 1e20;
    for(int j=0; j<2; j++)
    for(int i=0; i<2; i++) {
        vec2 rid = id + vec2(i,j)*o;
        vec2 r = p - s*rid;
        vec3 r3 = vec3(r.x,p3.y,r.y);
        float rad = hash(rid.xyy)*l;
        d = min(d,cylinder(r3,rad,rad*4.0));
    }
    if (hash(id.xyy)*l<4.0) d = 1e20;
    return d;
}

// correct way to repeat space every s units at l size
float repeated(vec3 p, float s, float l) {
    vec3 id = round(p/s);
    vec3 o = sign(p-s*id); // neighbor offset direction
    
    float d = 1e20;
    for(int k = 0; k < 2; k++)
    for(int j = 0; j < 2; j++)
    for(int i = 0; i < 2; i++) {
        vec3 rid = id + vec3(i,j,k)*o;
        vec3 r = p - s*rid;
        float rad = hash(rid)*l;
        d = min(d, sphere(r,rad));
    }

    return d;
}

// takes position, layer amplitude, layer amount, spacing, and radius/length of constructor shapes
float terrain(vec3 p, float a, uint layers, float s, float l) {
    float d = p.y; // base/first layer
    float n = d;
    // mountains
    for (int i = 0; i < layers; i++) { // noise octaves
        n = repeated(p, s, l);
        n = smax(n,d-a*s,0.3*s); // smoothly maximize octave a bit above current layer
        d = smin(n,d,0.3*s); // smoothly minimize current layer with octave
        p *= mat3(0.956,0,0.292,0,1,0,-0.292,0,0.956); // rotate next layer 17 degrees
        s *= 0.5; // reduce spacing and radius of next layer.
        l *= 0.5;
    }
    // trees
    //float t = trees(p+vec3(0,-128,0), 64.0, 5.0);

    return d;
}

uint material(vec3 p) {
    return uint(abs(p.y))%7u;
}

void main() {
    uvec3 pp = gl_GlobalInvocationID; // local chunk position
    if (clamp(pp, 0, chunkSize-1) != pp) return; // SO IMPORTANT
    vec3 p = vec3(pp)+cPos; // global position

    // gets terrain
    float d = terrain(p, 0.04, 7, 2560.0, 1280.0);
    uint mat = material(p);

    // sets chunk flag
    updateStoreFlag(d);

    // gets index within chunk.
    uint i = pp.x+chunkSize*(pp.y+chunkSize*pp.z);

    // sets data at index
    uint index = slot*chunkProbes+i; // index globally
    
    setMaterial(index,mat);
    setProbe(index,d);
}