// need to remember to keep updates inside chunks. Having dispatch overlap will break when they get shuffled around

#version 440 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

layout(std430, binding = 2) buffer ChunkIndexes {
    uint chunkIndexes[];
};

uniform vec3 uPos; // position of edit
uniform float uSize = 6.0; // size of edit 
uniform uint uType = 0; // type of edit
uniform uint uMaterial = 7;
uniform int uPlace = 0; // -1:place or 1:break

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.setgetH.comp


// gets edit function at position and size
float getEdit(vec3 p, uint i, float s) {
    switch (i) {
        case 0:
            return sphere(p, s);
        case 1:
            return box(p, vec3(s));
        default:
            return sphere(p, s);
    }
}

void main() {
    uvec3 pp = gl_GlobalInvocationID; // local probe position
    uvec3 cp = uvec3(round(uPos))-uvec3(round(uPos))%chunkSize;

    vec3 p = cp+pp;
    uvec3 lp = getLocalPos(p);

    float nd = getEdit(p-uPos, uType, uSize); // gets new distance
    float od = getProbe(lp); // gets current distance
    
    if (uPlace == -1) {
        if (nd<od) { // placing
            setMaterial(lp,uMaterial);
            setProbe(lp,nd);
        }
    } else {
        if (-nd>od) { // breaking
            //setMaterial(lp,uMaterial);
            setProbe(lp,-nd);
        }
    }

    // maybe implement neighbor check for unreset probes
}