#version 430 core

layout(local_size_x = 8, local_size_y = 8, local_size_z = 1) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer VoxelData {
    float voxelData[];
};

// screen data
layout(rgba32f, binding=0) uniform writeonly image2D screen;
uniform int screenWidth = 800;
uniform int screenHeight = 600;

const uint chunkSize = 1024u;

// takes position in chunk, and chunk size, and spits out positional index in chunkSize^3 array.
uint posToIndex(ivec3 p) {
    return p.x+chunkSize*(p.y+chunkSize*p.z);
}

// interpolates between surrounding precomputed probe distances.
float smoothDist(vec3 p) {
    ivec3 ip = ivec3(floor(p));
    vec3 f = fract(p);
    float d000 = voxelData[posToIndex(ip + ivec3(0,0,0))];
    float d100 = voxelData[posToIndex(ip + ivec3(1,0,0))];
    float d010 = voxelData[posToIndex(ip + ivec3(0,1,0))];
    float d110 = voxelData[posToIndex(ip + ivec3(1,1,0))];
    float d001 = voxelData[posToIndex(ip + ivec3(0,0,1))];
    float d101 = voxelData[posToIndex(ip + ivec3(1,0,1))];
    float d011 = voxelData[posToIndex(ip + ivec3(0,1,1))];
    float d111 = voxelData[posToIndex(ip + ivec3(1,1,1))];

    // need to interpolate every direction together, unlike last time.
    // x interpolation
    // maximized to -sqrt(3)/2.0 so distances can be negative inside of one voxel. Any lower and its solid.
    float x00 = mix(d000, d100, f.x);
    float x10 = mix(d010, d110, f.x);
    float x01 = mix(d001, d101, f.x);
    float x11 = mix(d011, d111, f.x);

    // y interpolation
    float y0 = mix(x00, x10, f.y);
    float y1 = mix(x01, x11, f.y);

    // z interpolation
    float d = mix(y0, y1, f.z);

    return d;
}
