#version 440 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

// 0-viewChunks is slots, viewChunks+ is flags
layout(std430, binding = 2) buffer ChunkData {
    uint chunkData[];
};

//include shaderheaders/4.3.constantsH.comp

// just sets all chunk indexes to unloaded
void main() {
    uvec3 cp = gl_GlobalInvocationID; // local chunk position
    if (clamp(cp, 0, viewSize-1) != cp) return; // SO IMPORTANT

    uint index = cp.x+viewSize*(cp.y+viewSize*cp.z);

    chunkData[index] = unloaded;
    chunkData[index+viewChunks] = unstored;
}