#version 430 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    float probeData[];
};
//const uint chunkSize = 512u;

//include shaders/4.3.constantsH.comp
//include shaders/4.3.functionsH.comp

float sdBox(vec3 p, vec3 b) {
    vec3 d = abs(p) - b;
    return min(max(d.x,max(d.y,d.z)),0.0) + length(max(d,0.0));
}

float smin(float a, float b, float k) {
    float h = max(k-abs(a-b),0.0);
    return min(a, b) - h*h*0.25/k;
}

float smax(float a, float b, float k) {
    float h = max(k-abs(a-b),0.0);
    return max(a, b) + h*h*0.25/k;
}

float sphere(vec3 p, vec3 id, float l) {
    float r = hash(id)*l;
    return length(p)-r;
}

// correct way to repeat space every s units
float repeated(vec3 p, float s, float l) {
    vec3 id = round(p/s);
    vec3 o = sign(p-s*id); // neighbor offset direction
    
    float d = 1e20;
    for(int k = 0; k < 2; k++)
    for(int j = 0; j < 2; j++)
    for(int i = 0; i < 2; i++) {
        vec3 rid = id + vec3(i,j,k)*o;
        vec3 r = p - s*rid;
        d = min(d, sphere(r,rid,l));
    }
    return d;
}

float terrain(vec3 p, float s, float l) {
    float d = p.y;
    float ol = l;
    for (int i = 0; i < 4; i++) {
        float n = repeated(p, s, l);
        n = smax(n,d-0.01*s,0.3*s);
        d = smin(n,d,0.3*s);
        p = mat3(0.00, 1.60, 1.20,
                -1.60, 0.72,-0.96,
                -1.20,-0.96, 1.28)*p;
        s*=0.5;
        l*=0.6;
    }
    return d;
}

void main() {
    uvec3 p = gl_GlobalInvocationID;
    float d = terrain(p/2.0, 320.0, 160.0);
    probeData[posToIndex(p)]=d;
}