#version 430 core

layout(local_size_x = 4, local_size_y = 4, local_size_z = 4) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

uniform vec3 uPos = vec3(32,32,32); // position of edit
uniform float uSize = 6.0; // size of edit 
uniform uint uType = 0; // type of edit
uniform uint uMaterial = 7;
uniform int uPlace = 0; // -1:place or 1:break

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.setgetH.comp


// gets edit function at position and size
float getEdit(vec3 p, uint i, float s) {
    switch (i) {
        case 0:
            return sphere(p, s);
        case 1:
            return box(p, vec3(s));
        default:
            return sphere(p, s);
    }
}

void main() {
    uvec3 p = gl_GlobalInvocationID; // probe position

    float nd = getEdit(p-uPos, uType, uSize); // gets new distance
    float od = getProbe(p); // gets current distance
    if (uPlace == -1) {
        if (nd<od) { // placing
            //setMaterial(p,uMaterial);
            setProbe(p,nd);
        }
    } else {
        if (-nd>od) { // breaking
            //setMaterial(p,uMaterial);
            setProbe(p,-nd);
        }
    }

    // maybe implement neighbor check for unreset probes
}