#version 440 core

layout(local_size_x = 8, local_size_y = 8) in; // 64 local threads is apparently sweet spot

layout(std430, binding = 0) buffer ProbeData {
    uint probeData[];
};

layout(std430, binding = 1) buffer MaterialData {
    uint materialData[];
};

layout(std430, binding = 2) buffer ChunkData {
    uint chunkData[];
};

layout(std430, binding = 3) buffer ColliderData { // temp for collider view
    uint colliderData[];
};

layout(binding = 1) uniform sampler2D depthMap; // depth and normal map
layout(rgba32f, binding=2) uniform writeonly image3D lightMap; // lighting map

uniform int screenWidth = 1;
uniform int screenHeight = 1;
uniform int lightSamples = 1;
uniform int lightFrames = 1;
uniform int lightFidelity = 1;
uniform vec3 worldPos;
uniform vec3 pPos;
uniform vec3 pDir;
uniform float iTime;

//include shaderheaders/4.3.constantsH.comp
//include shaderheaders/4.3.functionsH.comp
//include shaderheaders/4.3.materialsH.comp
//include shaderheaders/4.3.setgetH.comp
//include shaderheaders/4.3.samplingH.comp

float sunRay(vec3 ro, vec3 rd, vec3 normal) {
    // marching
    float light = dot(rd,normal);
    if (light<0) -0.5;
    float t = 0.1;

    for (int i = 0; i < lightSteps*2; i++) {

        vec3 p = ro+rd*t; // calculate ray position

        // distance to chunk border
        float cd = distToBorder(mod(p,float(chunkSize)), rd, vec3(chunkSize))+e;
        uint slot = chunkData[posToChunkIndex(getLocalPos(p, worldPos))];
        if (slot == unloaded || getStoreFlag(slot) == generating) { // if in unloaded, skip
            t+=cd+e;
            continue;
        }

        // distance to surface
        float d = getProbeWarped(p);
        if (d<5.0) d = smoothDist(p);
        t+=max(min(d,cd),1.0); // step ray

        // hit
        if (d < 0.1) {
            return -0.5;
        }
    }
    
    return light;
}

void main() {
    ivec2 fragCoord = ivec2(gl_GlobalInvocationID.xy); // light screen coordinates
    vec2 uv = vec2(fragCoord) / vec2(screenWidth, screenHeight); // sample from normal screen coords

    // sample depth map, and get normals
    vec4 depth = texture(depthMap, uv);
    vec3 normal = depth.xyz;

    // reconstruct position on surface of ray
    vec3 rd = getRayDir(fragCoord, vec2(screenWidth,screenHeight),pDir,1.0);
    vec3 ro = pPos-worldPos+center+rd*depth.w+normal;

    // get sun direction, some jitter applied to make softer shadows after noise filtering
    vec3 sun = normalize(vec3(normalize(vec3(sin(iTime*0.2),1.0,cos(iTime*0.2))))*20+hash3(vec3(fragCoord,1.0))-1);

    // cast ray from surface to sun
    float light = sunRay(ro, sun, normal);

    // store light value
    int count = lightSamples*lightFrames+1; // amount of other light passes
    imageStore(lightMap, ivec3(fragCoord,0), vec4(light*count*0.2));
}